### ISSUE TITLE
Use with API login

### ISSUE THREAD

**Issue by U54** [elie222/meteor-referrals#1]
This seems to only work for accounts-password, is there anyway to make it work with API logins such as accounts-google? I believe the issue is that it uses a preSignUpHook for the query parameters but since this requires a password I don't believe it will work for API logins. Is there anyway around this, maybe I'm just making a silly mistake, but I've been stuck on this for quite a while as it would fit perfectly with a project I'm working on.

Thanks!

**Comment by elie222** [comment]
Interesting. Will have to look into this. Didn't realise it didn't support social login. Will check now

**Comment by elie222** [comment]
Looks like you're right. I think the change should be made in accounts-core.

This code:
https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L203

Needs to be added somewhere in this file:
https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js

**Comment by elie222** [comment]
Added it as an issue here:
https://github.com/meteor-useraccounts/core/issues/669

**Comment by U54** [comment]
@elie222 Thanks I appreciate the response, love the package and it seems like it would work really well with my project but I've been stuck on this for a couple weeks now trying to find a workaround. Cant seem to find anything similar out there that work with social logins, I'll be sure to follow [meteor-useraccounts/core#669](https://github.com/meteor-useraccounts/core/issues/669)

**Comment by elie222** [comment]
If I have time I'll try update accounts core.

**Comment by elie222** [comment]
@U54 the package has been updated to support social login. See the readme. Would love if we found a less hacky solution.
